services:
  oracle-server-db:
    container_name: oracle-server-db
    image: gvenzl/oracle-xe:latest
    restart: always
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: 123456 #USER = SYSTEM | SID = XE