services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672      # Porta do protocolo AMQP
      - 15672:15672    # Porta da interface de gerenciamento web