version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  redis-ui:
    image: redislabs/redisinsight:1.14.0
    container_name: redis-ui
    ports:
      - "8001:8001"