version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

  redis-ui:
    image: redislabs/redisinsight:latest
    container_name: redis-ui
    ports:
      - "8001:8001"
    networks:
      - redis-network
    volumes:
      - ./redisinsight-config/connections.json:/db/redisinsight/connections.json

networks:
  redis-network:
    driver: bridge